apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: graphapp
data:
  # Backend endpoinnt
  # REACT_APP_API_BASE: "http://graphapp-alb-738384121.ap-northeast-1.elb.amazonaws.com"
  config.js: |
    window.RUNTIME_CONFIG = {
      API_BASE: "http://graphapp-alb-459164294.ap-northeast-1.elb.amazonaws.com"
    }

  # App configuration
  APP_ENV: "production"
  LOG_LEVEL: "INFO"