apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphapp-ingress
  namespace: graphapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-name: graphapp-alb
    alb.ingress.kubernetes.io/security-groups: sg-06d4f23148d132fcc # Only permit internet access from local laptops
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true" # When you specify custom frontend security groups, the controller will NOT automatically add rules to the backend security group
    alb.ingress.kubernetes.io/healthcheck-path: /health

spec:
  ingressClassName: alb
  rules:
  - http:
      paths:

      # Backend (Express)
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080

      # Frontend (React)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000